// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARow: typeof import('ant-design-vue/es')['Row']
    ArrowDownIcon: typeof import('./src/components/svg/ArrowDownIcon.vue')['default']
    ArrowLeftIcon: typeof import('./src/components/svg/ArrowLeftIcon.vue')['default']
    ArrowUpIcon: typeof import('./src/components/svg/ArrowUpIcon.vue')['default']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    Banner: typeof import('./src/components/layouts/banner/Banner.vue')['default']
    BlankLayout: typeof import('./src/components/layouts/blank-layout/BlankLayout.vue')['default']
    Body: typeof import('./src/components/layouts/Body.vue')['default']
    CloseIcon: typeof import('./src/components/svg/CloseIcon.vue')['default']
    ColOption1Icon: typeof import('./src/components/svg/ColOption1Icon.vue')['default']
    ColOption2Icon: typeof import('./src/components/svg/ColOption2Icon.vue')['default']
    DefaultLayout: typeof import('./src/components/layouts/default-layout/DefaultLayout.vue')['default']
    Dropdown1: typeof import('./src/components/layouts/dropdown/Dropdown-1.vue')['default']
    Footer: typeof import('./src/components/layouts/footer/Footer.vue')['default']
    GButton: typeof import('./src/components/base/GButton.vue')['default']
    GConfirmModal: typeof import('./src/components/base/GConfirmModal.vue')['default']
    GIcon: typeof import('./src/components/base/GIcon.vue')['default']
    GInput: typeof import('./src/components/base/GInput.vue')['default']
    GSelect: typeof import('./src/components/base/GSelect.vue')['default']
    GText: typeof import('./src/components/base/GText.vue')['default']
    Navbar: typeof import('./src/components/layouts/navbar/Navbar.vue')['default']
    NavbarFooterLayout: typeof import('./src/components/layouts/navbar-footer-layout/NavbarFooterLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/layouts/search-bar/SearchBar.vue')['default']
    SearchIcon: typeof import('./src/components/svg/SearchIcon.vue')['default']
    SortIcon: typeof import('./src/components/svg/SortIcon.vue')['default']
  }
}
